FROM velonica2227/minian-docker-base:latest

RUN apt-get update -yy && \
    apt-get install -yy --no-install-recommends libgtk-3-dev locales && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8

RUN pip install --upgrade pip && \
    pip install --upgrade -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxpython
