FROM velonica2227/minian-docker-base:latest

RUN DEBIAN_FRONTEND=noninteractive apt-get update -yy && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yy --no-install-recommends libgtk-3-dev

RUN pip install --upgrade pip && \
    pip install --upgrade --no-cache-dir pysimplegui
